[package]
name = "binance"
version = "0.1.0"
authors = ["ax <ax@xxx.xxx>"]
edition = "2018"

[dependencies]
reqwest = "0.9.4"
serde_json = "*"
serde_derive = "*"
serde = "*"
hmac = "*"
sha2 = "*"
hex = "*"
